version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: warden_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5439:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - warden_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  warden_postgres_data:
